### ISSUE TITLE
Loading data issues

### ISSUE THREAD

**Issue by KaIi-github** [neuromorphs/tonic#191]
```
Traceback (most recent call last):
  File "D:\Data\PycharmProjects\SNN-NMNIST-Object-Recognition\train.py", line 68, in <module>
    train_set = VNMNISTDataset(
  File "D:\Data\PycharmProjects\SNN-NMNIST-Object-Recognition\VNMNISTDataset.py", line 18, in __init__
    self.dataset = tonic.datasets.NMNIST(save_to=os.path.abspath('./data'),
  File "D:\Software\Anaconda3\envs\snnor\lib\site-packages\tonic\datasets\nmnist.py", line 74, in __init__
    self.download()
  File "D:\Software\Anaconda3\envs\snnor\lib\site-packages\tonic\dataset.py", line 26, in download
    download_and_extract_archive(
  File "D:\Software\Anaconda3\envs\snnor\lib\site-packages\tonic\download_utils.py", line 323, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "D:\Software\Anaconda3\envs\snnor\lib\site-packages\tonic\download_utils.py", line 119, in download_url
    url = _get_redirect_url(url, max_hops=max_redirect_hops)
  File "D:\Software\Anaconda3\envs\snnor\lib\site-packages\tonic\download_utils.py", line 63, in _get_redirect_url
    with urllib.request.urlopen(
  File "D:\Software\Anaconda3\envs\snnor\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Software\Anaconda3\envs\snnor\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "D:\Software\Anaconda3\envs\snnor\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "D:\Software\Anaconda3\envs\snnor\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "D:\Software\Anaconda3\envs\snnor\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "D:\Software\Anaconda3\envs\snnor\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060]
```

I've downloaded the dataset, but it's still trying to download it for me, and it gets this error

**Comment by KaIi-github** [comment]
When I removed the self.download() in the nmnist.py, it could be trained normally.
It doesn't seem to recognize my dataset path.

**Comment by biphasic** [comment]
Hello, I just downloaded NMNIST from scratch successfully. 

```python 
import tonic

testset = tonic.datasets.NMNIST(save_to='./data', train=False)
```
Your issue could be related to #190  where sometimes the host refuses requests if there are too many downloads. Are you using the latest tonic version? Maybe clear out the data directory?

**Comment by KaIi-github** [comment]
Thanks for your reply, I'll try these options.

**Comment by biphasic** [comment]
closing for now, please re-open if you still have issues.
