### ISSUE TITLE
Can't download CIFAR10-DVS by tonic

### ISSUE THREAD

**Issue by msjun23** [neuromorphs/tonic#223]
I tried to use dataset, CIFAR10-DVS, but it's unavailable. It seems server issue.
Can you check it please?

Here is my error log

```
>>> tonic.datasets.CIFAR10DVS(save_to='./tmp')
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/python_ws/SNN-Torch-Practice/lib/python3.8/site-packages/tonic/datasets/cifar10dvs.py", line 86, in __init__
    self.download()
  File "/home/user/python_ws/SNN-Torch-Practice/lib/python3.8/site-packages/tonic/dataset.py", line 35, in download
    download_and_extract_archive(
  File "/home/user/python_ws/SNN-Torch-Practice/lib/python3.8/site-packages/tonic/download_utils.py", line 323, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/home/user/python_ws/SNN-Torch-Practice/lib/python3.8/site-packages/tonic/download_utils.py", line 119, in download_url
    url = _get_redirect_url(url, max_hops=max_redirect_hops)
  File "/home/user/python_ws/SNN-Torch-Practice/lib/python3.8/site-packages/tonic/download_utils.py", line 63, in _get_redirect_url
    with urllib.request.urlopen(
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1383, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

```

**Comment by fabhertz95** [comment]
Have you tried to open directly the link of the dataset?

**Comment by msjun23** [comment]
http://cifar10dvs.ridger.top/CIFAR10DVS.zip

Isn't it the link of CIFAR10-DVS? I found it at [official Tonic docs](https://tonic.readthedocs.io/en/latest/_modules/tonic/datasets/cifar10dvs.html#CIFAR10DVS), and also this link is doesn't work.

**Comment by fabhertz95** [comment]
Then the link is broken and the Tonic code has nothing to do with it.

**Comment by biphasic** [comment]
Hey @msjun23 , as @fabhertz95 mentioned sometimes the server that hosts the data breaks because of too many requests, because the owner moved the data or many other possible reasons. I suggest to try again in 24h, and if it still doesn't work, contact the dataset owners.

**Comment by biphasic** [comment]
@msjun23 did you try again afterwards? Is this still an issue?

**Comment by msjun23** [comment]
@biphasic  Yes, the link doesn't work. I think it's right to have a problem with the server..

**Comment by biphasic** [comment]
I sent an email to the dataset owner. Will see if they respond

**Comment by NikolaZubic** [comment]
@msjun23 In [cifar10dvs.py](https://github.com/neuromorphs/tonic/blob/develop/tonic/datasets/cifar10dvs.py) , you can edit lines 32-34.
Replace it with:
```
url = "https://figshare.com/ndownloader/articles/4724671/versions/2"

filename = "4724671.zip"
```

This is a working link for downloading CIFAR10DVS.

**Comment by biphasic** [comment]
hey @NikolaZubic , how do you decode the aedat v2 ?

**Comment by biphasic** [comment]
I uploaded the dataset to a new link and updated the url in bc5dca2cb60954b1e4482961ab584236427e4eb5, this should work now again! Please go ahead and try it using the latest Tonic version

**Comment by msjun23** [comment]
@biphasic @NikolaZubic Thanks for your help! Now it works
